---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: pietOS
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - starship
        - vim-default-editor
        - zcfan
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - nano-default-editor

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.freedesktop.Platform.ffmpeg-full//24.08
          - com.nextcloud.desktopclient.nextcloud
          - com.valvesoftware.Steam
          - com.vscodium.codium
          - com.yubico.yubioath
          - net.lutris.Lutris
          - org.kde.isoimagewriter
          - org.keepassxc.KeePassXC
          - org.libreoffice.LibreOffice
          - org.sabnzbd.sabnzbd
          - org.signal.Signal
          - org.videolan.VLC
          - cc.arduino.IDE2
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
