# image will be published to ghcr.io/<user>/<name>
name: bluebuild-custom
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-packages.yml

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - com.nextcloud.desktopclient.nextcloud
        - com.rtosta.zapzap
        - com.valvesoftware.Steam
        - com.visualstudio.code
        - com.yubico.yubioath
        - fr.handbrake.ghb
        - io.github.ungoogled_software.ungoogled_chromium
        - io.missioncenter.MissionCenter
        - org.filezillaproject.Filezilla
        - org.gimp.GIMP
        - org.keepassxc.KeePassXC
        - org.libreoffice.LibreOffice
        - org.sabnzbd.sabnzbd
        - org.signal.Signal
        - org.speedcrunch.SpeedCrunch
        - org.telegram.desktop
        - org.videolan.VLC
        - org.kde.yakuake
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
  
  - type: systemd
    system:
      enabled:
        - podman.socket
        - cups-browsed.service
        - usbmuxd.service
        - fstrim.timer    

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

