name: bluebuild-custom
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 40
modules:
  - from-file: common-packages.yml
  
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: systemd
    system:
      enabled:
        - podman.socket
        - cups-browsed.service
        - usbmuxd.service
        - fstrim.timer    

  - type: signing